

team_dict = {'Miami Dolphins': 'MIA',
            'Houston Oilers': 'OIL',
            'San Diego Chargers': 'SD',
            'Green Bay Packers': 'GB',
            'Atlanta Falcons': 'ATL',
            'Buffalo Bills': 'BUF',
            'Detroit Lions': 'DET',
            'Pittsburgh Steelers': 'PIT',
            'San Francisco 49ers': 'SF',
            'St. Louis Cardinals': 'SLC',
            'Washington Redskins': 'WAS',
            'Los Angeles Rams': 'LA',
            'Cleveland Browns': 'CLE',
            'Dallas Cowboys': 'DAL',
            'Denver Broncos': 'DEN',
            'Minnesota Vikings': 'MIN',
            'New York Jets': 'NYJ',
            'Oakland Raiders': 'OAK',
            'Philadelphia Eagles': 'PHI',
            'Baltimore Colts': 'BAC',
            'Boston Patriots': 'BOS',
            'Kansas City Chiefs': 'KC',
            'New York Giants': 'NYG',
            'Chicago Bears': 'CHI',
            'New Orleans Saints': 'NO',
            'Cincinnati Bengals': 'CIN',
            'New England Patriots': 'NE',
            'Seattle Seahawks': 'SEA',
            'Tampa Bay Buccaneers': 'TB',
            'Los Angeles Raiders': 'LA_R',
            'Indianapolis Colts': 'IND',
            'Phoenix Cardinals': 'PHX',
            'Arizona Cardinals': 'ARI',
            'Jacksonville Jaguars': 'JAC',
            'St. Louis Rams': 'STL',
            'Carolina Panthers': 'CAR',
            'Baltimore Ravens': 'BAL',
            'Tennessee Oilers': 'TEN_O',
            'Tennessee Titans': 'TEN',
            'Houston Texans': 'HOU',
            'Los Angeles Chargers': 'LAC'}